### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ClaudiuGeorgiu** [ClaudiuGeorgiu/miniCAP#1]
* [x] Delete generated CAPTCHAs after a certain amount of time (10min)
* [x] Delete CAPTCHAs that have been validated
* [x] Delete CAPTCHAs after 3 unsuccessful validation requests
* [x] Stress test with [Locust](https://github.com/locustio/locust)
